### PR TITLE
PUSH WeChat and TG Message

### PR DESCRIPTION
**Pull request by Jason6111**

### CODE REVIEW

**Comment by smallprogram** [comment]
你好，我不太明白{{ secrets.TGID }}和{{ secrets.PUSH_PLUS_TOKEN }}在那来的？

**Comment by Jason6111** [comment]
从tg上建立自己机器人的到的id 跟token 库里建立key就行 tgid tgtoken 可以自己改名字 push_plus_token是从微信pushplus获得的

发自我的iPhone

**Comment by Jason6111** [comment]
参考

https://github.com/danshui-git/shuoming/blob/master/ms.md

发自我的iPhone

**Comment by Jason6111** [comment]
https://github.com/danshui-git/shuoming/blob/master/bot.md

发自我的iPhone

**Comment by smallprogram** [comment]
I invite you to participate in this project. I have read the PR and feel very good. But at the moment I don't think I can use it myself. Email push from Github is enough. If you like it, please add it to the project for processing.

**Pull request merged**
